//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wypozyczenia
    {
        public int ID_wypozyczenia { get; set; }
        public int ID_Gry { get; set; }
        public int ID_pracownika { get; set; }
        public int ID_klienta { get; set; }
        public System.DateTime Data_wypozyczenia { get; set; }
    
        public virtual Gry Gry { get; set; }
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Zwroty Zwroty { get; set; }
    }
}
