//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zwroty
    {
        public int ID_wypozyczenia { get; set; }
        public int ID_pracownika { get; set; }
        public System.DateTime data_zwrotu { get; set; }
        public int doplaty { get; set; }
    
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Wypozyczenia Wypozyczenia { get; set; }
    }
}
